### Signup
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
		"login": "user1",
		"password": "password1"
}

### Signin
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
		"login": "user1",
		"password": "password1"
}

### Check
GET http://localhost:8000/auth/check

### Logout
GET http://localhost:8000/auth/logout