name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: go build -v ./...
      env:
        GOFLAGS: "-mod=vendor"

    - name: Test
      run: go test -v ./...
      env:
        GOFLAGS: "-mod=vendor"